// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from 'react';
import * as Slider from './Slider.bs.js';
import * as Belt_Array from 'rescript/lib/es6/belt_Array.js';

var logos = Belt_Array.map(
	Belt_Array.map(Belt_Array.range(1, 7), function (prim) {
		return String(prim);
	}),
	function (i) {
		return 'https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/' + i + '.png';
	}
);

var style = {
	background: '#e3e3e3',
	display: 'flex',
	height: '100vh',
};

function App(Props) {
	return React.createElement(
		'div',
		{
			style: style,
		},
		React.createElement(Slider.make, {
			children: Belt_Array.map(logos, function (src) {
				return React.createElement(Slider.$$Image.make, {
					src: src,
				});
			}),
			width: '250',
			height: '100',
		})
	);
}

var make = App;

export { logos, style, make };
/* logos Not a pure module */
